version: '3.9'


services:
  chat:
    build: .
    ports:
      - "8000:8000"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    depends_on:
      - chat
        #  grafana:
        #  image: grafana/grafana
        #  ports:
        # - "3000:3000" #grafana ui
        # depends_on:
        #  - prometheus
        # volumes:
        #  - grafana-storage:/var/lib/grafana

        #volumes:
        #  grafana-storage:
